### ISSUE TITLE
typing in chat will delete certin letters 

### ISSUE THREAD

**Issue by Dio0000** [SilverstoneMC/Silverstone#52] opened 2021-06-23 04:42 UTC
### World the issue occured in

Main

### My Minecraft username

xXI___DIO___IXx

### What I was doing before/when the issue occurred

typing

### What happened

the chat delete words. eg. type /back it will come out like ack

### What was supposed to happen

suppose to be normal actually was normal today morning

**Comment by JasonHorkles** [comment] 2021-06-24 06:18
Are you sure it's not some glitch with your client? There should be nothing causing that to happen and I can't reproduce it

**Comment by Dio0000** [comment] 2021-06-24 06:32
Yeah I think it was on my part

**Comment by JasonHorkles** [comment] 2021-06-24 06:34
If it happens again try testing on another server to see if it happens there too
Going to close the issue for now but if it seems to be a server issue in the future feel free to leave a comment here :)

**Closed by JasonHorkles** 2021-06-24 06:34 UTC
Labels: Bug-Unconfirmed, Low Priority
